language: csharp
solution: AspNet.WebApi.CookiesPassthrough.sln
mono:
  - 5.16.0
install:
  - nuget restore AspNet.WebApi.CookiesPassthrough.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild AspNet.WebApi.CookiesPassthrough.sln /p:Configuration=Release 
  - mono ./testrunner/NUnit.Console.3.9.0/tools/nunit-console.exe ./AspNet.WebApi.CookiesPassthrough.Tests/bin/Release/AspNet.WebApi.CookiesPassthrough.Tests.dll
